services:
  api:
    build: backend
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - realcloud-network
  database:
    image: postgres
    environment:
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_DB=hrmanager
    networks:
      - realcloud-network

networks:
  realcloud-network:
    driver: bridge
